---
- name: Update Homebrew
  homebrew: update_homebrew=yes
  tags: brew

- name: Tap fonts
  homebrew_tap: tap=caskroom/fonts state=present
  tags: brew

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - ansible
    - curl
    - fasd
    - git
    - highlight
    - hub
    - nmap
    - python3
    - vim
    - watch
    - wget
    - zsh
    - tree
    - tmux
    - openssl
    - coreutils
    - findutils
    - htop
  tags: brew

- name: Install apps with Homebrew Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - sublime-text
    - vlc
    - font-hack
    - font-meslo-for-powerline
    - font-menlo-for-powerline
    - font-source-code-pro-for-powerline
    - font-ubuntu-mono-derivative-powerline
    - font-roboto-mono-for-powerline
  tags: brew

- name: Cleanup Brew packages
  command: brew cleanup
  tags: brew
